/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.DB4OUtil.DB4OUtil;
import Business.DeliveryMan.DeliveryMan;
import Business.EcoSystem;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.LoginPage.LoginPageJPanel;
import userinterface.LoginPage.SignUpJPanel;

/**
 *
 * @author SHRISHTI
 */
public class ManageDeliveryManJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageDeliveryManJPanel
     */
    
    private JPanel container;
    private EcoSystem ecosystem;
    private DB4OUtil dB4OUtil;
    
    public ManageDeliveryManJPanel(JPanel container,EcoSystem ecosystem,DB4OUtil dB4OUtil) {
        initComponents();
        this.container= container;
        this.ecosystem= ecosystem;
        this.dB4OUtil= dB4OUtil;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton = new javax.swing.JButton();
        logoutButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        deliveryManListJTable = new javax.swing.JTable();
        addDeliveryManButton = new javax.swing.JButton();
        removeDeliveryManButton = new javax.swing.JButton();

        backButton.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 12)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        logoutButton1.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 12)); // NOI18N
        logoutButton1.setText("Logout");
        logoutButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 20)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Manage Delivery Men");

        deliveryManListJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Delivery Man ID", "Delivery Man Name", "Orders Delivered"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        deliveryManListJTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deliveryManListJTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(deliveryManListJTable);

        addDeliveryManButton.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 12)); // NOI18N
        addDeliveryManButton.setText("Add Delivery Man");
        addDeliveryManButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDeliveryManButtonActionPerformed(evt);
            }
        });

        removeDeliveryManButton.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 12)); // NOI18N
        removeDeliveryManButton.setText("Remove Delivery Man");
        removeDeliveryManButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeDeliveryManButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(addDeliveryManButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(removeDeliveryManButton, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(289, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton)
                    .addComponent(logoutButton1))
                .addGap(43, 43, 43)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addDeliveryManButton)
                    .addComponent(removeDeliveryManButton))
                .addContainerGap(256, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed

        container.remove(this);
        CardLayout layout = (CardLayout)container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_backButtonActionPerformed

    private void logoutButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButton1ActionPerformed
        // TODO add your handling code here:
        container.removeAll();
        LoginPageJPanel lpp= new LoginPageJPanel(container, ecosystem, dB4OUtil);
        container.add("LoginPageJPanel", lpp);
        CardLayout crdLyt = (CardLayout) container.getLayout();
        crdLyt.next(container);
        dB4OUtil.storeSystem(ecosystem);
    }//GEN-LAST:event_logoutButton1ActionPerformed

    private void deliveryManListJTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deliveryManListJTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_deliveryManListJTableMouseClicked

    private void addDeliveryManButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDeliveryManButtonActionPerformed
        // TODO add your handling code here:
        SignUpJPanel sup= new SignUpJPanel(container, ecosystem, dB4OUtil,"DeliveryMan");
        container.add("SignUpJPanel",sup);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_addDeliveryManButtonActionPerformed

    private void removeDeliveryManButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeDeliveryManButtonActionPerformed
        // TODO add your handling code here:

        DefaultTableModel dtm = (DefaultTableModel) deliveryManListJTable.getModel();
        int rowNumber = deliveryManListJTable.getSelectedRow();
        if (rowNumber != -1) {
            int result = JOptionPane.showConfirmDialog(null, "Confirm?");
            if (result == JOptionPane.YES_OPTION) {
                DeliveryMan d=this.ecosystem.getDeliveryManDirectory().findDeliveryMan(dtm.getValueAt(rowNumber, 0).toString());
                this.ecosystem.getUserAccountDirectory().removeUserAccount(d.getDeliveryManAccount().getUsername());
                this.ecosystem.getDeliveryManDirectory().removeDeliveryMan(dtm.getValueAt(rowNumber, 0).toString());
                dtm.removeRow(rowNumber);
                populateTable();
            }

        } else {
            JOptionPane.showMessageDialog(null, "Please select delivery man to remove.");
        }
    }//GEN-LAST:event_removeDeliveryManButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDeliveryManButton;
    private javax.swing.JButton backButton;
    private javax.swing.JTable deliveryManListJTable;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logoutButton1;
    private javax.swing.JButton removeDeliveryManButton;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) deliveryManListJTable.getModel();
        dtm.setRowCount(0);
        for (String s : this.ecosystem.getDeliveryManDirectory().getDeliveryManList().keySet()) {
            DeliveryMan d = this.ecosystem.getDeliveryManDirectory().getDeliveryManList().get(s);
            Object row[] = new Object[3];
            row[0] = d.getDelId();
            row[1] = d.getFirstName();
            int count=0;
            for(String st: d.getDeliveryManAccount().getOrders().getOrderDirectory().keySet()){
                if(d.getDeliveryManAccount().getOrders().getOrderDirectory().get(st).getStatus().equals("Delivered")){
                    count++;
                }
            }
            row[2] = count;
            dtm.addRow(row);
        }
    }
}
