/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uiPatient;

import java.awt.CardLayout;
import javax.swing.InputVerifier;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.MyStringVerifier;
import model.Patient;
import model.Person;

/**
 *
 * @author SHRISHTI
 */
public class CreatePatientJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreatePatientJPanel
     */
    private Person person;
    private JPanel userProcessContainer;
    
    public CreatePatientJPanel(JPanel upc, Person person) {
        initComponents();
        this.userProcessContainer = upc;
        this.person = person;
        addVerifiers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        primaryDocNameJLabel = new javax.swing.JLabel();
        prefferedPharmacyJLabel = new javax.swing.JLabel();
        patientIDJTextField = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        primaryDocNameJTextField = new javax.swing.JTextField();
        prefferedPharmacyJTextField = new javax.swing.JTextField();
        addPatientJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        patientIDJLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        primaryDocNameJLabel.setBackground(new java.awt.Color(255, 255, 255));
        primaryDocNameJLabel.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N
        primaryDocNameJLabel.setForeground(new java.awt.Color(255, 0, 204));
        primaryDocNameJLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        primaryDocNameJLabel.setText("Primary Doctor Name :");

        prefferedPharmacyJLabel.setBackground(new java.awt.Color(255, 255, 255));
        prefferedPharmacyJLabel.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N
        prefferedPharmacyJLabel.setForeground(new java.awt.Color(255, 0, 204));
        prefferedPharmacyJLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        prefferedPharmacyJLabel.setText("Preffered Pharmacy :");

        patientIDJTextField.setBackground(new java.awt.Color(255, 255, 255));
        patientIDJTextField.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N
        patientIDJTextField.setForeground(new java.awt.Color(255, 0, 204));
        patientIDJTextField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        backJButton.setBackground(new java.awt.Color(255, 255, 255));
        backJButton.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        backJButton.setForeground(new java.awt.Color(255, 0, 204));
        backJButton.setText("<<Back");
        backJButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        primaryDocNameJTextField.setBackground(new java.awt.Color(255, 255, 255));
        primaryDocNameJTextField.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N
        primaryDocNameJTextField.setForeground(new java.awt.Color(255, 0, 204));
        primaryDocNameJTextField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        prefferedPharmacyJTextField.setBackground(new java.awt.Color(255, 255, 255));
        prefferedPharmacyJTextField.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N
        prefferedPharmacyJTextField.setForeground(new java.awt.Color(255, 0, 204));
        prefferedPharmacyJTextField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        addPatientJButton.setBackground(new java.awt.Color(255, 255, 255));
        addPatientJButton.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        addPatientJButton.setForeground(new java.awt.Color(255, 0, 204));
        addPatientJButton.setText("Add Patient");
        addPatientJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPatientJButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Patient Details");

        patientIDJLabel.setBackground(new java.awt.Color(255, 255, 255));
        patientIDJLabel.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N
        patientIDJLabel.setForeground(new java.awt.Color(255, 0, 204));
        patientIDJLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        patientIDJLabel.setText("Patient ID :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(450, 450, 450)
                        .addComponent(prefferedPharmacyJLabel)
                        .addGap(179, 179, 179)
                        .addComponent(prefferedPharmacyJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(136, 136, 136)
                                .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(214, 214, 214)
                                .addComponent(patientIDJLabel))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(primaryDocNameJLabel)))
                        .addGap(179, 179, 179)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(primaryDocNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(patientIDJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(616, 616, 616)
                .addComponent(addPatientJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {patientIDJTextField, prefferedPharmacyJTextField, primaryDocNameJTextField});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {patientIDJLabel, prefferedPharmacyJLabel, primaryDocNameJLabel});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {addPatientJButton, backJButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backJButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(patientIDJLabel)
                        .addComponent(patientIDJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(primaryDocNameJLabel)
                    .addComponent(primaryDocNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prefferedPharmacyJLabel)
                    .addComponent(prefferedPharmacyJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(addPatientJButton)
                .addContainerGap(824, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {patientIDJTextField, prefferedPharmacyJTextField, primaryDocNameJTextField});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {patientIDJLabel, prefferedPharmacyJLabel, primaryDocNameJLabel});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {addPatientJButton, backJButton});

    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void addPatientJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPatientJButtonActionPerformed
        // TODO add your handling code here:
        if (checkBlankInput())
        {   
            Patient patient = new Patient();
            patient.setPatientID(patientIDJTextField.getText());
            patient.setDoctor(primaryDocNameJTextField.getText());
            patient.setPharmacy(prefferedPharmacyJTextField.getText());
            //Adding Patient to Person
            person.setPatient(patient);
            JOptionPane.showMessageDialog(this, "Patient added!!", "Update",
                JOptionPane.INFORMATION_MESSAGE);
            clearFields();
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Please enter all values",
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_addPatientJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPatientJButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel patientIDJLabel;
    private javax.swing.JTextField patientIDJTextField;
    private javax.swing.JLabel prefferedPharmacyJLabel;
    private javax.swing.JTextField prefferedPharmacyJTextField;
    private javax.swing.JLabel primaryDocNameJLabel;
    private javax.swing.JTextField primaryDocNameJTextField;
    // End of variables declaration//GEN-END:variables

    private void addVerifiers() {
        InputVerifier stringVerifier = new MyStringVerifier();
        patientIDJTextField.setInputVerifier(stringVerifier);
        primaryDocNameJTextField.setInputVerifier(stringVerifier);
        prefferedPharmacyJTextField.setInputVerifier(stringVerifier);
    }

    private boolean checkBlankInput() {
        if(patientIDJTextField.getText().length()== 0
                || primaryDocNameJTextField.getText().length()== 0
                || prefferedPharmacyJTextField.getText().length()== 0)
        {
            return false;
        }
        else{
            return true;
        }
    }

    private void clearFields() {
        patientIDJTextField.setText("");
        primaryDocNameJTextField.setText("");
        prefferedPharmacyJTextField.setText("");
    }
}
