/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.logging.Logger;
//import java.lang.System.Logger.Level;
//import java.lang.System.Logger.Level;
import javax.imageio.ImageIO;
//import java.util.logging.Logger;
import java.util.logging.Level;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.Product;

/**
 *
 * @author SHRISHTI
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    Product product;
    BufferedImage picture;
    BufferedImage picture1;

    public CreateJPanel(Product product) {
        initComponents();
        this.product = product;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblDOB = new javax.swing.JLabel();
        lblGeographicData = new javax.swing.JLabel();
        lblMobileNum = new javax.swing.JLabel();
        txtGeographicData = new javax.swing.JTextField();
        txtMobileNum = new javax.swing.JTextField();
        txtVehicleIden = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        lblHomeNumber = new javax.swing.JLabel();
        txtHomeNumber = new javax.swing.JTextField();
        lblFaxNumber = new javax.swing.JLabel();
        txtFaxNumber = new javax.swing.JTextField();
        lblEmailID = new javax.swing.JLabel();
        txtEmailID = new javax.swing.JTextField();
        lblSSN = new javax.swing.JLabel();
        txtSSN = new javax.swing.JTextField();
        lblMedicalRecordNumber = new javax.swing.JLabel();
        txtMedicalRecordNumber = new javax.swing.JTextField();
        lblHPBN = new javax.swing.JLabel();
        txtHPBN = new javax.swing.JTextField();
        lblBankAccNum = new javax.swing.JLabel();
        txtBankAccNum1 = new javax.swing.JTextField();
        lblBankAccNum2 = new javax.swing.JLabel();
        txtBankAccNum2 = new javax.swing.JTextField();
        lblCertNum = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtLicenceNum = new javax.swing.JTextField();
        lblVehicleIden = new javax.swing.JLabel();
        txtDeviceIden = new javax.swing.JTextField();
        lblDeviceIden = new javax.swing.JLabel();
        lblLinkdedIn = new javax.swing.JLabel();
        txtLinkedIn = new javax.swing.JTextField();
        txtIPAddr = new javax.swing.JTextField();
        lblIPAddr = new javax.swing.JLabel();
        lblBiometricIden = new javax.swing.JLabel();
        lblUploadPic = new javax.swing.JLabel();
        txtUniqueIden = new javax.swing.JTextField();
        lblUploadPic1 = new javax.swing.JLabel();
        btnAttachBiometricIden = new javax.swing.JButton();
        lblBankAccNUm2 = new javax.swing.JLabel();
        btnAttachPhoto = new javax.swing.JButton();
        txtUploadPic = new javax.swing.JTextField();
        txtBiometricIdenPath = new javax.swing.JTextField();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(0, 0));
        setPreferredSize(new java.awt.Dimension(0, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Create Profile");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(-910, 10, 2872, 39));

        lblName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName.setText("Name :");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 60, 30));

        lblDOB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDOB.setText("Date of Birth :");
        add(lblDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 79, 30));

        lblGeographicData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGeographicData.setText("Address :");
        add(lblGeographicData, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 109, 30));

        lblMobileNum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMobileNum.setText("Mobile Number :");
        add(lblMobileNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 89, 30));
        add(txtGeographicData, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 200, 30));

        txtMobileNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMobileNumActionPerformed(evt);
            }
        });
        add(txtMobileNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 200, 30));

        txtVehicleIden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVehicleIdenActionPerformed(evt);
            }
        });
        add(txtVehicleIden, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 140, 200, 30));

        btnSave.setForeground(new java.awt.Color(0, 0, 153));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 550, 100, 30));

        lblHomeNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHomeNumber.setText("Home Number :");
        add(lblHomeNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 89, 30));
        add(txtHomeNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 200, 30));

        lblFaxNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFaxNumber.setText("Fax Number :");
        add(lblFaxNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 89, 30));

        txtFaxNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFaxNumberActionPerformed(evt);
            }
        });
        add(txtFaxNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 200, 30));

        lblEmailID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmailID.setText("Email ID :");
        add(lblEmailID, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 89, 30));
        add(txtEmailID, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 200, 30));

        lblSSN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSSN.setText("SSN :");
        add(lblSSN, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 98, 30));

        txtSSN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSSNActionPerformed(evt);
            }
        });
        add(txtSSN, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 200, 30));

        lblMedicalRecordNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMedicalRecordNumber.setText("Medical Record Number :");
        add(lblMedicalRecordNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 139, 30));

        txtMedicalRecordNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMedicalRecordNumberActionPerformed(evt);
            }
        });
        add(txtMedicalRecordNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 200, 30));

        lblHPBN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHPBN.setText("Health Plan Beneficiary Number :");
        add(lblHPBN, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 181, 30));

        txtHPBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHPBNActionPerformed(evt);
            }
        });
        add(txtHPBN, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 460, 200, 30));

        lblBankAccNum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBankAccNum.setText("Checking Account Number :");
        add(lblBankAccNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 181, 30));

        txtBankAccNum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBankAccNum1ActionPerformed(evt);
            }
        });
        add(txtBankAccNum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 500, 200, 30));

        lblBankAccNum2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBankAccNum2.setText("Bank Account Number 2 :");
        add(lblBankAccNum2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1660, 540, 181, 30));

        txtBankAccNum2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBankAccNum2ActionPerformed(evt);
            }
        });
        add(txtBankAccNum2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 540, 200, 30));

        lblCertNum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCertNum.setText("Certificate/Licence Number :");
        add(lblCertNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, 164, 30));

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 200, 30));

        txtLicenceNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLicenceNumActionPerformed(evt);
            }
        });
        add(txtLicenceNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 100, 200, 30));

        lblVehicleIden.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVehicleIden.setText("Vehicle Identifier :");
        add(lblVehicleIden, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, 164, 30));

        txtDeviceIden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeviceIdenActionPerformed(evt);
            }
        });
        add(txtDeviceIden, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 180, 200, 30));

        lblDeviceIden.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDeviceIden.setText("Device Identifier :");
        add(lblDeviceIden, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, 164, 30));

        lblLinkdedIn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLinkdedIn.setText("LinkedIn :");
        add(lblLinkdedIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 220, 120, 30));

        txtLinkedIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLinkedInActionPerformed(evt);
            }
        });
        add(txtLinkedIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 220, 200, 30));

        txtIPAddr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIPAddrActionPerformed(evt);
            }
        });
        add(txtIPAddr, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 260, 200, 30));

        lblIPAddr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIPAddr.setText("Internet Protocol Address :");
        add(lblIPAddr, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, 164, 30));

        lblBiometricIden.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBiometricIden.setText("Biometric Identifier :");
        add(lblBiometricIden, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 380, 164, 30));

        lblUploadPic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUploadPic.setText("Upload Photo :");
        add(lblUploadPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 340, 164, 30));

        txtUniqueIden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUniqueIdenActionPerformed(evt);
            }
        });
        add(txtUniqueIden, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 300, 200, 30));

        lblUploadPic1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUploadPic1.setText("Unique Identifier :");
        add(lblUploadPic1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 300, 150, 30));

        btnAttachBiometricIden.setForeground(new java.awt.Color(0, 0, 153));
        btnAttachBiometricIden.setText("Attach");
        btnAttachBiometricIden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttachBiometricIdenActionPerformed(evt);
            }
        });
        add(btnAttachBiometricIden, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 380, -1, -1));

        lblBankAccNUm2.setText("Savings Account Number 2  :");
        add(lblBankAccNUm2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, 160, 30));

        btnAttachPhoto.setForeground(new java.awt.Color(0, 0, 153));
        btnAttachPhoto.setText("Attach");
        btnAttachPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttachPhotoActionPerformed(evt);
            }
        });
        add(btnAttachPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 340, -1, -1));

        txtUploadPic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUploadPicActionPerformed(evt);
            }
        });
        add(txtUploadPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 340, 200, 30));
        add(txtBiometricIdenPath, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 380, 200, 30));
        add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 200, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void txtVehicleIdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVehicleIdenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVehicleIdenActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        Date date = null;
        //DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
        //LocalDateTime now = LocalDateTime.now();  
        //String compare=dtf.format(now);
        if (txtName.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Name is Empty!");
        } else if (!Pattern.matches("([a-zA-Z',.-]+( [a-zA-Z',.-]+)*){2,30}", txtName.getText())) {
            JOptionPane.showMessageDialog(this, "Name is invalid!");
        } else if (txtGeographicData.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Address is Empty!");
        } else if (jDateChooser2.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Date is Empty!");
        } else if (txtMobileNum.getText().isEmpty() || !Pattern.matches("[0-9]{10}", txtMobileNum.getText())) {
            JOptionPane.showMessageDialog(this, "Mobile number is incorrect!");
        } else if (txtHomeNumber.getText().isEmpty() || !Pattern.matches("[0-9]{10}", txtHomeNumber.getText())) {
            JOptionPane.showMessageDialog(this, "Home number is incorrect!");
        } else if (txtFaxNumber.getText()
                .isEmpty() || !Pattern.matches("[0-9]{7}", txtFaxNumber.getText())) {
            JOptionPane.showMessageDialog(this, "Incorrect Fax Number!");
        } else if (txtEmailID.getText().isEmpty() || !Pattern.matches("^[a-zA-Z0-9+_.-]+@[a-zA-Z0-9.-]+$", txtEmailID.getText())) {
            JOptionPane.showMessageDialog(this, "Incorrect Email ID format!");
        } //SSN 856-45-6789
        else if (txtSSN.getText().isEmpty() || !Pattern.matches("^(?!666|000|9\\d{2})\\d{3}-(?!00)\\d{2}-(?!0{4})\\d{4}$", txtSSN.getText())) {
            JOptionPane.showMessageDialog(this, "Incorrect SSN format!");
        } //medical record number HP1234
        else if (txtMedicalRecordNumber.getText().isEmpty() || !Pattern.matches("[a-zA-Z{2}0-9]{6}", txtMedicalRecordNumber.getText())) {
            JOptionPane.showMessageDialog(this, "Incorrect Medical Record Number");
        } //health plan benificary AB123456
        else if (txtHPBN.getText().isEmpty() || !Pattern.matches("[a-zA-Z{2}0-9]{8}", txtHPBN.getText())) {
            JOptionPane.showMessageDialog(this, "Incorrect Health Plan Record Number");
        } else if (txtBankAccNum1.getText().isEmpty() || !Pattern.matches("[0-9]{10}", txtBankAccNum1.getText())) {
            JOptionPane.showMessageDialog(this, "Incorrect Checking Account Number 1!");
        } else if (txtBankAccNum2.getText().isEmpty() || !Pattern.matches("[0-9]{10}", txtBankAccNum2.getText())) {
            JOptionPane.showMessageDialog(this, "Incorrect Saving Account Number 1!");
        } else if (txtLicenceNum.getText().isEmpty() || !Pattern.matches("^[^+_=/*?@#$%&()'\"|â„;:{}.,`~<>}{][^\\\\]{1,20}$", txtLicenceNum.getText())) {
            JOptionPane.showMessageDialog(this, "Licence Number is Incorrect!");
        } else if (txtVehicleIden.getText().isEmpty() || !Pattern.matches("[(a-z|A-Z|0-9)]{17}", txtVehicleIden.getText())) {
            JOptionPane.showMessageDialog(this, "Incorrext Vehicle Identification Number");
        } else if (txtDeviceIden.getText().isEmpty() || !Pattern.matches("[0-9]{14}", txtDeviceIden.getText())) {
            JOptionPane.showMessageDialog(this, "Device number is incorrect!");
        } else if (txtIPAddr.getText().isEmpty() || !Pattern.matches("[0-9]{3}.[0-9]{3}.[0-9]{1}.[0-9]{2}", txtIPAddr.getText())) {
            JOptionPane.showMessageDialog(this, "Incorrect IP Address");  //192.168.4.74
        } else if (txtUniqueIden.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Unique Identifier is empty!");
        } else if (txtUploadPic.getText().isEmpty()){
        
            JOptionPane.showMessageDialog(this, "Upload a Picture"); 
        } else if (txtBiometricIdenPath.getText().isEmpty()){
        
            JOptionPane.showMessageDialog(this, "Upload a Biometric Identifier"); 
        }
        else {
            product.setName(txtName.getText());
            date = jDateChooser2.getDate();
            product.setDob(date);
            product.setGeographicData(txtGeographicData.getText());

            product.setMobileNumber(Long.parseLong(txtMobileNum.getText()));
            product.setHomeNumber(Long.parseLong(txtHomeNumber.getText()));
            product.setFaxNumber(Long.parseLong(txtFaxNumber.getText()));
            product.setEmail(txtEmailID.getText());
            product.setSSN(txtSSN.getText());
            product.setMedicalRecNum(txtMedicalRecordNumber.getText());
            product.setHpBeneficiaryNo(txtHPBN.getText());
            product.setBankAccNo1(Long.parseLong(txtBankAccNum1.getText()));
            product.setBankAccNo2(Long.parseLong(txtBankAccNum2.getText()));
            product.setLicenceNo(txtLicenceNum.getText());
            product.setVehicleIdentifier(Long.parseLong(txtVehicleIden.getText()));
            product.setDeviceIdentifier(Long.parseLong(txtDeviceIden.getText()));
            product.setLinkedIn(txtLinkedIn.getText());
            product.setIPAddress(txtIPAddr.getText());
            product.setUniqueIdentifier(txtUniqueIden.getText());

            JOptionPane.showMessageDialog(this, "Person information saved.");
            txtName.setText("");
            txtGeographicData.setText("");
            jDateChooser2.setCalendar(null);
            txtMobileNum.setText("");
            txtHomeNumber.setText("");
            txtFaxNumber.setText("");
            txtEmailID.setText("");
            txtSSN.setText("");
            txtMedicalRecordNumber.setText("");
            txtHPBN.setText("");
            txtBankAccNum1.setText("");
            txtBankAccNum2.setText("");
            txtLicenceNum.setText("");
            txtVehicleIden.setText("");
            txtDeviceIden.setText("");
            txtLinkedIn.setText("");
            txtIPAddr.setText("");
            txtUniqueIden.setText("");

        }

    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtSSNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSSNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSSNActionPerformed

    private void txtMedicalRecordNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedicalRecordNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedicalRecordNumberActionPerformed

    private void txtMobileNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMobileNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMobileNumActionPerformed

    private void txtHPBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHPBNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHPBNActionPerformed

    private void txtBankAccNum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBankAccNum1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBankAccNum1ActionPerformed

    private void txtBankAccNum2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBankAccNum2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBankAccNum2ActionPerformed

    private void txtFaxNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFaxNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFaxNumberActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtLicenceNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLicenceNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLicenceNumActionPerformed

    private void txtDeviceIdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeviceIdenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeviceIdenActionPerformed

    private void txtLinkedInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLinkedInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLinkedInActionPerformed

    private void txtIPAddrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIPAddrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIPAddrActionPerformed

    private void txtUniqueIdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUniqueIdenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUniqueIdenActionPerformed

    private void btnAttachPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttachPhotoActionPerformed
        JFileChooser browse = new JFileChooser();
        FileNameExtensionFilter extensionFilter = new FileNameExtensionFilter("Only jpg and jpeg Supported", "jpeg", "jpg");
        browse.setFileFilter(extensionFilter);
        browse.showOpenDialog(null);
        File f = browse.getSelectedFile();
        String filename = f.getName();
        txtUploadPic.setText(filename);
        picture = new BufferedImage(100, 100, BufferedImage.TYPE_INT_ARGB);

        try {
            picture = ImageIO.read(f);
        } catch (IOException ex) {
            Logger.getLogger(CreateJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        product.setPhoto(picture);
    }//GEN-LAST:event_btnAttachPhotoActionPerformed

    private void txtUploadPicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUploadPicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUploadPicActionPerformed

    private void btnAttachBiometricIdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttachBiometricIdenActionPerformed
        JFileChooser browse1 = new JFileChooser();
        FileNameExtensionFilter extensionFilter1 = new FileNameExtensionFilter("Only jpg and jpeg Supported", "jpeg", "jpg");
        browse1.setFileFilter(extensionFilter1);
        browse1.showOpenDialog(null);
        File f1 = browse1.getSelectedFile();
        String filename1 = f1.getName();
        txtBiometricIdenPath.setText(filename1);
        picture1 = new BufferedImage(100, 100, BufferedImage.TYPE_INT_ARGB);

        try {
            picture1 = ImageIO.read(f1);
        } catch (IOException ex) {
            Logger.getLogger(CreateJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        product.setBiometricIden(picture1);
    }//GEN-LAST:event_btnAttachBiometricIdenActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAttachBiometricIden;
    private javax.swing.JButton btnAttachPhoto;
    private javax.swing.JButton btnSave;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel lblBankAccNUm2;
    private javax.swing.JLabel lblBankAccNum;
    private javax.swing.JLabel lblBankAccNum2;
    private javax.swing.JLabel lblBiometricIden;
    private javax.swing.JLabel lblCertNum;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblDeviceIden;
    private javax.swing.JLabel lblEmailID;
    private javax.swing.JLabel lblFaxNumber;
    private javax.swing.JLabel lblGeographicData;
    private javax.swing.JLabel lblHPBN;
    private javax.swing.JLabel lblHomeNumber;
    private javax.swing.JLabel lblIPAddr;
    private javax.swing.JLabel lblLinkdedIn;
    private javax.swing.JLabel lblMedicalRecordNumber;
    private javax.swing.JLabel lblMobileNum;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUploadPic;
    private javax.swing.JLabel lblUploadPic1;
    private javax.swing.JLabel lblVehicleIden;
    private javax.swing.JTextField txtBankAccNum1;
    private javax.swing.JTextField txtBankAccNum2;
    private javax.swing.JTextField txtBiometricIdenPath;
    private javax.swing.JTextField txtDeviceIden;
    private javax.swing.JTextField txtEmailID;
    private javax.swing.JTextField txtFaxNumber;
    private javax.swing.JTextField txtGeographicData;
    private javax.swing.JTextField txtHPBN;
    private javax.swing.JTextField txtHomeNumber;
    private javax.swing.JTextField txtIPAddr;
    private javax.swing.JTextField txtLicenceNum;
    private javax.swing.JTextField txtLinkedIn;
    private javax.swing.JTextField txtMedicalRecordNumber;
    private javax.swing.JTextField txtMobileNum;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtUniqueIden;
    private javax.swing.JTextField txtUploadPic;
    private javax.swing.JTextField txtVehicleIden;
    // End of variables declaration//GEN-END:variables
}
