/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uiPerson;

import java.awt.CardLayout;
import javax.swing.InputVerifier;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.MyNumericVerifier;
import model.MyStringVerifier;
import model.Person;

/**
 *
 * @author SHRISHTI
 */
public class ViewUpdatePersonDetailsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewUpdatePersonDetailsJPanel
     */
    
    private Person person;
    private JPanel userProcessContainer;
    private Boolean isEdit = Boolean.FALSE;
    
    public ViewUpdatePersonDetailsJPanel(JPanel userProcessContainer, Person person, Boolean isEdit) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.person = person;
        this.isEdit = isEdit;
        addVerifiers();
        populatePatientDetails();
        modifyTextFields(this.isEdit);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        patientNameJLabel = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        AgeJLabel = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        patientNameJLabel1 = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        patientNameJLabel2 = new javax.swing.JLabel();
        txtResidence = new javax.swing.JTextField();
        patientNameJLabel3 = new javax.swing.JLabel();
        txtCommunity = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Patient Details");

        patientNameJLabel.setBackground(new java.awt.Color(255, 255, 255));
        patientNameJLabel.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N
        patientNameJLabel.setForeground(new java.awt.Color(255, 0, 204));
        patientNameJLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        patientNameJLabel.setText("First Name :");

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 0, 204));
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(255, 255, 255));
        btnEdit.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 0, 204));
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(255, 255, 255));
        btnSave.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 0, 204));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        AgeJLabel.setBackground(new java.awt.Color(255, 255, 255));
        AgeJLabel.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N
        AgeJLabel.setForeground(new java.awt.Color(255, 0, 204));
        AgeJLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        AgeJLabel.setText("Age :");

        txtFirstName.setBackground(new java.awt.Color(255, 255, 255));
        txtFirstName.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N

        txtAge.setBackground(new java.awt.Color(255, 255, 255));
        txtAge.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N

        patientNameJLabel1.setBackground(new java.awt.Color(255, 255, 255));
        patientNameJLabel1.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N
        patientNameJLabel1.setForeground(new java.awt.Color(255, 0, 204));
        patientNameJLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        patientNameJLabel1.setText("Last Name :");

        txtLastName.setBackground(new java.awt.Color(255, 255, 255));
        txtLastName.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N

        patientNameJLabel2.setBackground(new java.awt.Color(255, 255, 255));
        patientNameJLabel2.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N
        patientNameJLabel2.setForeground(new java.awt.Color(255, 0, 204));
        patientNameJLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        patientNameJLabel2.setText("Residence :");

        txtResidence.setBackground(new java.awt.Color(255, 255, 255));
        txtResidence.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N

        patientNameJLabel3.setBackground(new java.awt.Color(255, 255, 255));
        patientNameJLabel3.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N
        patientNameJLabel3.setForeground(new java.awt.Color(255, 0, 204));
        patientNameJLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        patientNameJLabel3.setText("Community :");

        txtCommunity.setBackground(new java.awt.Color(255, 255, 255));
        txtCommunity.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(1039, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(patientNameJLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(189, 189, 189)
                        .addComponent(txtCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(patientNameJLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(189, 189, 189)
                        .addComponent(txtResidence, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(patientNameJLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(189, 189, 189)
                            .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(AgeJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(patientNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(189, 189, 189)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(374, 374, 374))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientNameJLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientNameJLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AgeJLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtResidence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientNameJLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientNameJLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnEdit)
                    .addComponent(btnSave))
                .addContainerGap(637, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        modifyTextFields(true);
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:

        if (checkBlankInput()) {
            person.setAge(Integer.parseInt(txtAge.getText()));
            person.setFirstName(txtFirstName.getText());
            person.setLastName((txtLastName.getText()));
            person.setResidence(txtResidence.getText());
            person.setCommunity(txtCommunity.getText());
            JOptionPane.showMessageDialog(this, "Person updated!!",
                "Update", JOptionPane.INFORMATION_MESSAGE);
            modifyTextFields(false);
        } else {
            JOptionPane.showMessageDialog(this, "Please enter correct values",
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AgeJLabel;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel patientNameJLabel;
    private javax.swing.JLabel patientNameJLabel1;
    private javax.swing.JLabel patientNameJLabel2;
    private javax.swing.JLabel patientNameJLabel3;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtCommunity;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtResidence;
    // End of variables declaration//GEN-END:variables

    private void addVerifiers() {
        InputVerifier integerVerifier = new MyNumericVerifier();
        txtAge.setInputVerifier(integerVerifier);
        InputVerifier stringVerifier = new MyStringVerifier();
        txtFirstName.setInputVerifier(stringVerifier);
        InputVerifier stringVerifier1 = new MyStringVerifier();
        txtLastName.setInputVerifier(stringVerifier1);
        InputVerifier stringVerifier2 = new MyStringVerifier();
        txtCommunity.setInputVerifier(stringVerifier2);
    }

    private void populatePatientDetails() {
         txtFirstName.setText(person.getFirstName());
         txtLastName.setText(person.getLastName());
         txtAge.setText(String.valueOf(person.getAge()));
         txtResidence.setText(person.getResidence());
         txtCommunity.setText(person.getCommunity());
    }

    private void modifyTextFields(Boolean isEdit) {
        if (isEdit) {
            txtFirstName.setEnabled(true);
            txtLastName.setEnabled(true);
            txtAge.setEnabled(true);
            txtResidence.setEnabled(true);
            txtCommunity.setEnabled(true);
        } else {
            txtFirstName.setEnabled(false);
            txtLastName.setEnabled(false);
            txtAge.setEnabled(false);
            txtResidence.setEnabled(false);
            txtCommunity.setEnabled(false);
        }
    }

    private boolean checkBlankInput() {
        if (txtAge.getText().length() == 0
                || txtFirstName.getText().length() == 0
                || txtLastName.getText().length() == 0
                || txtResidence.getText().length() == 0
                || txtCommunity.getText().length() == 0) {
            return false;
        } else {
            return true;
        }
    }
}
